version: "3.8"

services:
  db:
    image: 6664c41da9e4
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: